package libxml_2_0

import _ "unsafe"

const UDEBUG = 0
const UCLNNOAUTOCLEANUP = 1
const UDISABLERENAMING = 0
const UNODEFAULTINCLUDEUTFHEADERS = 0
const UOVERRIDECXXALLOCATION = 1
const UENABLETRACING = 0
const UCONFIGENABLEPLUGINS = 0
const UENABLEDYLOAD = 1
const UCHECKDYLOAD = 1
const UDEFAULTSHOWDRAFT = 1
const ULIBSUFFIXCNAMESTRING = ""
const UCONFIGONLYCOLLATION = 0
const UCONFIGNOFILEIO = 0
const UCONFIGNOCONVERSION = 0
const UCONFIGONLYHTMLCONVERSION = 0
const UCONFIGNOLEGACYCONVERSION = 0
const UCONFIGNONORMALIZATION = 0
const UCONFIGUSEMLPHRASEBREAKING = 0
const UCONFIGNOBREAKITERATION = 0
const UCONFIGNOIDNA = 0
const UCONFIGUSEWINDOWSLCIDMAPPINGAPI = 1
const UCONFIGNOCOLLATION = 0
const UCONFIGNOFORMATTING = 0
const UCONFIGNOMF2 = 0
const UCONFIGNOTRANSLITERATION = 0
const UCONFIGNOREGULAREXPRESSIONS = 0
const UCONFIGNOSERVICE = 0
const UCONFIGHAVEPARSEALLINPUT = 1
const UCONFIGNOFILTEREDBREAKITERATION = 0
